version: "3.7"
services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Asia/Jakarta'
      WEBPASSWORD: 'password'
      ServerIP: 192.168.0.12
      FTL_CMD: debug
      DNSMASQ_LISTENING: all
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - '.etc/pihole/:/etc/pihole/'
      - '.etc/dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: always


